# Generated by Django 2.0.2 on 2019-02-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyinfo',
            name='sex',
            field=models.CharField(max_length=1),
        ),
    ]
