# Generated by Django 2.0.2 on 2019-02-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190215_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyinfo',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
