# Generated by Django 2.0.2 on 2019-02-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_testinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('passwd', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='BabyInfo',
        ),
        migrations.DeleteModel(
            name='TestInfo',
        ),
    ]
