# Generated by Django 2.0.2 on 2019-02-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20190226_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.RemoveField(
            model_name='bloginfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='title',
            field=models.CharField(max_length=30, primary_key='title', serialize=False),
        ),
    ]
