# Generated by Django 2.0.2 on 2019-03-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20190228_0208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscontrol',
            options={'ordering': ('-date', 'ip')},
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='date',
            field=models.DateTimeField(blank=True,null=True),
            preserve_default=False,
        ),
    ]
