# Generated by Django 2.0.2 on 2019-03-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20190305_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='date',
            field=models.DateTimeField(blank=True,null=True),
        ),
    ]
