# Generated by Django 2.0.2 on 2019-03-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20190305_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
