# Generated by Django 2.0.2 on 2019-03-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20190305_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscontrol',
            options={'ordering': ('ip',)},
        ),
        migrations.RemoveField(
            model_name='accesscontrol',
            name='date',
        ),
    ]
