# Generated by Django 2.0.2 on 2019-03-06 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20190305_1633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessControl',
        ),
    ]
