# Generated by Django 2.0.2 on 2019-03-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_delete_accesscontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('ip',),
            },
        ),
    ]
