# Generated by Django 2.0.2 on 2019-03-06 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_auto_20190306_0129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscontrol',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='accesscontrol',
            name='ip',
        ),
    ]
