# Generated by Django 2.0.2 on 2019-03-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_auto_20190306_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='ip_address',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
    ]
