# Generated by Django 2.0.2 on 2019-03-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_auto_20190306_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='访问人数')),
            ],
        ),
    ]
