# Generated by Django 2.0.2 on 2019-03-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_accessnumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloginfo',
            options={'ordering': ('title',)},
        ),
    ]
