# Generated by Django 2.0.2 on 2019-03-12 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_auto_20190310_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
